### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by Sliverious** [steos/php-quickcheck#13]
I found this repository as I was fiddling around with the idea of creating a similar library and I was wondering whether this repository is still considered to be alive and if not, what considerations led to its discontinued development? I read some remarks about interoperability issues with PHPUnit but couldn't quite make out if that was the main problem.

Anyway, I hope to see this kind of testing framework be more prevalent in the php world so any response would be appreciated!

**Comment by steos** [comment]
Hi!

Thanks for your interest. The project is definitely still alive. Virtually all of the functionality of clojure.test.check has been implemented so it's basically feature complete.

What is lacking is a more fully featured test runner (where PHPUnit integration would be nice) and I haven't had the chance to really stress test it in a production environment. I'm happy to accept contributions though!

Happy holidays!
