### ISSUE TITLE
Problematic implementation (speed and memory)

### ISSUE THREAD

**Issue by Vinai** [steos/php-quickcheck#14]
## Description

PHP runs out of memory after roughly 30 seconds (during shrinking according to the stacktrace).  
The PHP  `memory_limit` set to 2GB.

Here is a simple test that reliably reproduces the issue on my machine

```php
<?php declare(strict_types=1);

use PHPUnit\Framework\TestCase;
use QCheck\Generator as Gen;
use QCheck\Quick;

class QcheckTest extends TestCase
{
    public function testStrings(): void
    {
        $prop = Gen::forAll([Gen::strings()], function ($s): bool {
            $this->assertLessThan(100, strlen($s));
            return true;
        });
        $this->assertNotFail(Quick::check(135, $prop, ['echo' => true]));
    }

    private function assertNotFail(array $result): void
    {
        if (isset($result['fail'])) {
            printf("Tests runs: %d, seed: %s, failing value: \n", $result['num_tests'], $result['seed']);
            var_export($result['fail'][0]);
            throw $result['result'] instanceof Exception ?
                $result['result'] :
                new \PHPUnit\Framework\Exception(
                    sprintf('Property check returned result: "%s"', var_export($result['result'], true))
                );
        }
    }
}
```

I love clojure.test.check and would love to use PBT in PHP, too. The php-quickcheck API is very nice to use from a developer perspective, but I'm afraid the implementation makes it unusable for practical work. I only took a cursory glance, but from that I guess some of the recursion needs to be replaced with mutating iteration.

Currently I'm using https://github.com/giorgiosironi/eris/ to do PBT, but unfortunately the maintainer isn't responsive. Even though there are issues with Eris, too, it at least allows me to use it during work.
I would very much like to be able to use php-quickcheck, since the API matches what I'm use to from clojure.test.check more closely.

### Additional Details

OOM is reached after roughly 30 seconds.
I am running php with `-dxdebug.max_nesting_level=9999`, otherwise the stack is blown quickly.
PHP Versions: 7.3.8, 7.2.21 and 7.1.26.
Machine: 2.2GHz Intel i7 MBP, 32GB RAM.

**Comment by steos** [comment]
Hi! Thanks for the detailed report. I will try to look into it in the next couple of days.

**Comment by steos** [comment]
The memory issue should be resolved now. Shrinking will take a while though, especially for this particular example since it has to test a huge amount of permutations.

**Comment by Vinai** [comment]
Thank you! I can confirm that indeed now the test completes without running OOM.

On my machine it takes roughly 50 seconds for the ~100 test runs until it fails.

The same test with Eris takes 60 ms with roughly the same number of test runs...

I haven't dug into this, but from what I can see the shrink algorithm that Eris uses is much simpler.
Strings are shrunk by dropping one char at the time, while with your implementation all chars seem to be shrunk towards `\0` in addition to the string being shortened (judging by the smallest shrunk values).

It would be awesome if you can find a way for some improvements in regards to performance.

Is it possible to specify shrink strategies for generators maybe?

**Comment by Vinai** [comment]
I very much appreciate your efforts and that you published php-quickcheck.
Do you think the performance can't be improved any more in PHP?

I used my very unscientific example test from above to compare different implementations. 

```clj
(tc/quick-check 135 (prop/for-all [s gen/string]
                                  (< (count s) 100)))
```
and in Eris
```php
$this->forAll(gen\string())
     ->then(function ($s) {
         $this->assertLessThan(100, strlen($s));
     });
```

| QuickCheck Implementation | time | nodes visited |
|----------|--------|--------|
| clojure.test.check (Clojure) | 315ms | 10218 |
| clojure.test.check (ClojureScript) | 1191ms | 10212 |
| php-quickcheck | 43s | 10205 |
| Eris | 114ms | limited shrinking only | 

I don't find PHP to be generally that slow in comparison, so I'm just curious to get your thoughts....

**Comment by steos** [comment]
Yeah right, the strings are generated based on arrays of ints which all shrink individually. 

What you want can be done by making them not shrink in the first place. I added a small helper function `dontShrink` which removes the children of the shrink tree of the generator instance. 

Now you can do this instead of using `Gen::strings()` directly:

```php
function strings() {
    return Gen::chars()
        ->dontShrink()
        ->intoArrays()
        ->toStrings();
}
```

With this generator your example finishes in about a second on my machine (vs. about a minute for `Gen::strings()`)

**Comment by steos** [comment]
Just saw your last comment about performance. Did you try to disable xdebug and maybe enable the gmp extension? xdebug will have a pretty big performance hit and the RNG should be faster with gmp available. 
With xdebug enabled your example takes about a minute on my machine, without it's a couple of seconds.

**Comment by Vinai** [comment]
Wow, you are right. My apologies. Since I didn't have a debug server listening I didn't expect xdebug to have such a big impact.
When I disable the module the test runs in 3.8 seconds (so only about twice as long as cljs :D)

This is great, I can use php-quickcheck now :) Thanks again

**Comment by Vinai** [comment]
Also, thanks for `dontShrink` and `toStrings`!
