### ISSUE TITLE
PHP 7.3 or 7.4?

### ISSUE THREAD

**Issue by Chemaclass** [steos/php-quickcheck#27]
Why would you have the `7.3` as min requirement in the `composer.json` but `7.4` in the Dev Setup?

- What about updating the `composer.json` to require the `>=7.4` version?

Otherwise, I would downgrade the dev setup Dockerfile to use the `php:7.3`.

I say this because I believe it's better to develop something using the same tool-versions as the real/end environment where it's going to be used.

**Comment by jwdunne** [comment]
Yes, this is confusing. When I open a PR, I wrote assuming PHP 7.4 minimum. The build didn’t stop me from doing that and I used arrow functions, which are quite elegant when used with QuickCheck.

I recommend either making 7.4 the min version or add an argument with PHP version to the docker image so we can set up a build that tests against all supported versions?

This would be helpful and I’m happy to open a PR with either option @steos ?

**Comment by steos** [comment]
Yeah agreed. I originally wanted to go to 7.4 with the changes for 2.0 but decided to stay at 7.3 as minimum, mostly due to feedback from @Vinai . I didn't update the dev setup though. I'd appreciate any PR that fixes this as long as it keeps 7.3 support.

**Comment by jwdunne** [comment]
Ah, what was the reasoning about keeping 7.3?

We could actually do something like this so it's easier to test new versions too:

https://github.com/jwdunne/enguard
https://github.com/jwdunne/enguard/blob/master/Makefile
https://github.com/jwdunne/enguard/blob/master/Dockerfile 
https://github.com/jwdunne/enguard/blob/master/scripts/test.sh

We'd do something similar but with PHP instead. It'd be pretty straight forward to expand the matrix along other version lines too, e.g PHPUnit version, so we can uncover integration regressions quickly.

It's more complex than just straight 7.4 support but it's working well for 4 versions of Python :)

**Comment by Chemaclass** [comment]
@steos any plans so far to update to 7.4? Just curious :)
If you decided to stay with 7.3 it's all right as well. I created the PR to "required the 7.4 as the minimum" to see how it would visually change. Because arrow functions for this project would be used every time... anyway, I understand that you might want to keep it open for older versions, or is there any other reason why you want to keep as min the 7.3?

**Comment by steos** [comment]
Yeah I decided to stay with 7.3 since it was requested and I think it makes sense, at least as long as 7.3 is still actively supported and there is no real need to have 7.4 as minimum. I don't want to unnecessarily exclude 7.3 users from being able to use this library and I don't think there is a downside for 7.4 users.
